# fly.toml file generated for mp3pam-api-laravel on 2022-06-26T13:38:45-04:00

app = "mp3pam-api-laravel"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  LOG_LEVEL = "info"
  APP_URL = "https://mp3pam-api-laravel.fly.dev"

  DB_CONNECTION = "pgsql"
  DB_HOST = "top2.nearest.of.mp3pam-api-laravel-db.internal"
  DB_PORT = 5433
  DB_DATABASE = "mp3pam_api_laravel"
  DB_USERNAME = "mp3pam_api_laravel"
  DB_PASSWORD = "yNhvZNu5IUcxQWy"

  APP_DEBUG = true
  APP_LOG_LEVEL = "debug"

  BROADCAST_DRIVER = "log"
  CACHE_DRIVER = "file"
  SESSION_DRIVER = "file"
  QUEUE_DRIVER = "sync"

  MAIL_DRIVER = "smtp"
  MAIL_HOST = "smtp.mailtrap.io"
  MAIL_PORT = 2525
  # MAIL_USERNAME = null
  # MAIL_PASSWORD = null
  # MAIL_ENCRYPTION = null

  # PUSHER_APP_ID =
  # PUSHER_APP_KEY =
  # PUSHER_APP_SECRET =

  # Admin
  ADMIN_NAME = 'Jean Gérard Bousiquot'
  ADMIN_USERNAME = 'jgbneatdesign'
  ADMIN_EMAIL = 'jgbneatdesign@gmail.com'
  ADMIN_PASSWORD = "asdf,,,"
  ADMIN_TELEPHONE = '8099055510'

  # Search
  SCOUT_DRIVER = "tntsearch"
  TNTSEARCH_AS_YOU_TYPE = true

  # Lighthouse Cache
  # LIGHTHOUSE_CACHE_ENABLE = false

  # WASABI
  WASABI_KEY = "AR6K1TTHKLAGMSA1J9OU"
  WASABI_SECRET = "2J6HqYidF7na9yklSpQBtz8bggtXToeFaDV1XnWZ"
  WASABI_REGION = "us-west-1"
  WASABI_BUCKET = "mp3pam.com"
  WASABI_ENDPOINT = "https://s3.us-west-1.wasabisys.com"

  # JWT secret
  JWT_SECRET = "K6MXvvtC76J48fHhfwqX9X1JmNEyJzoeUDAaQ9LQjDrJruk8Sjzut9pE703XPagm"

  # Facebook
  FACEBOOK_CLIENT = "232624100615967"
  FACEBOOK_SECRET = "656f8d5c1f588cf908f983036a8edc34"
  FACEBOOK_REDIRECT = "https://mp3pam.com/auth/facebook"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "5s"
